#!/bin/bash
# Opens a default viewer for different kind of files
# based on MIME types.
# Improved version of ED


function pat()
{
	echo "$1" | grep -q "$2"
}

# Defer functions into background and disown them
function defer()
{
	case $1 in
		less|dhex|timg|links|cvlc)
			"$@"
			;;
		*)
			"$@" &
			disown $!
			;;
	esac
}
for f in "$@"; do
	mime=$(file --brief --mime-type $f)
	if pat $mime "^image"; then
		if [[ "$DISPLAY" != "" ]]; then
			defer feh $f
		else
			defer timg $f
			if [[ "$2" != "" ]]; then
				sleep 1
			fi
		fi
	elif pat $mime "^video"; then
		if [[ "$DISPLAY" != "" ]]; then
			defer mplayer $f
		else
			defer cvlc $f
		fi
	elif [[ "$mime" == "text/html" ]]; then
		defer links $f
	elif pat $mime "^text"; then
		defer less $f
	elif [[ "$mime" == "application/pdf" ]]; then
		defer mupdf $f
	elif [[ "$mime" == "application/octet-stream" ]]; then
		defer dhex $f
	else
		echo $f "unrecognized format:" $mime
	fi;
done
